### ISSUE TITLE
A question about intervals

### ISSUE THREAD

**Issue by cristiancavalli** [dglogik/node_io.dart#2]
Hey Everyone,

Thanks for making this shim as this has made it very easy to run my dartJS apps with node libs. But I seem to have run into an issue with setInterval. In using the new dart js package: https://pub.dartlang.org/packages/js and in creating a new periodic timer from dart->main() I seem to get an infinite loop of callback completion happening at every tick. Essentially, I create an interval of 10 seconds and the interval immediately executes and continues to re-execute every tick. I think that this has to do with the action not being popped off the queue but from my limited study I still don't really understand how the command queue works thus far. I came up with a very temporary stop-gap solution for my needs:
(at the top level)

```
var createInterval = setInterval;
var endInterval = clearInterval;
var self = this;
if (typeof global != "undefined") self = global;  // Node.js.

(function(self) {
...
```

and where the setInterval property is set:

```
self.setInterval = function ( f, ms ) {
  timerList.push(createInterval(f, ms));
  return timerList.length-1;
}
self.clearInterval = function ( id ) {
  endInterval( timerList[id] );
}
```

It seems that the repo has been dormant for a little bit and I'm guessing that since dart is actively changing this broke some functionality in honey.
I would like to correct this error in the right way but I'm still a bit confused by the event queue and why the wrapping env doesn't just provide properties which point to native node functions.

Thanks!
Cris

**Comment by mbullington** [comment]
Hello!

Sorry for the delayed response, but I believe the latest commit should fix any issues you were having. The latest commit almost completely rewrote the honey tool (this was previously neglected as it's no longer used in production). 

Issues fixed:
- intervals, any node.js bugs that rise from using the dart2js d8.js preamble. I replaced it with the node.js preamble that we use in daily production at DGLogik, and can also be found [here](https://github.com/mbullington/node_preamble.dart). Your concerns with the d8.js wrapper/preamble are very valid, and are addressed with this.
- Module system now works, including require, etc, making honey a full testing environment.
- Running honey with multiple files will now execute them all in the same scope.

Please try this with the rewritten version of honey, thanks for helping keep this little (and extremely useful) tool alive!
Michael Bullington

**Comment by cristiancavalli** [comment]
@mbullington This is awesome. 
Thanks so much for your contributions. I am absolutely in love with this tool.
